name: Build and Release Debian Package

on:
  push:
    tags:
      - 'v*'  # 仅当推送的标签以 "v" 开头时触发（例如 v1.0.0）

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - uses: actions/checkout@v4

      # 构建 Debian 包
      - uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=binary --no-sign

      # 创建 GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      # 上传 Debian 包作为 Release Asset
      - name: Upload Debian Package to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: debian/artifacts/faultinjectorllm_0.1.0.deb
          asset_name: faultinjectorllm_0.1.0.deb
          asset_content_type: application/vnd.debian.binary-package