name: Build Debian Package

on: push

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - uses: actions/checkout@v4

      # 构建 Debian 包
      - uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=binary --no-sign

      # 上传构建的 Debian 包作为 Artifact
      - uses: actions/upload-artifact@v4
        with:
          path: debian/artifacts/
          name: debian_package